### ISSUE TITLE
[Blueprint] LEGO Ninjago (2012)

### ISSUE THREAD

**Issue by flowcool** [CollinHeist/TitleCardMaker-Blueprints#105]
### Series Name

LEGO Ninjago

### Series Year

2012

### Creator Username

flowcool

### Blueprint Description

Anime Card with the nice font Ninjago Font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Lego Ninja go",
      "delete_missing": true,
      "file": "Ninjago.otf",
      "title_case": "title"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![LEGO Ninjago (2012) - S02E03](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/e46c62f8-9f08-439b-b885-548b0a4515cf)

### Zip of Font Files

[Ninjago.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12319720/Ninjago.zip)

**Comment by CollinHeist** [comment]
Thanks ! /create-blueprint
