### ISSUE TITLE
[Blueprint] Peacemaker (2022)

### ISSUE THREAD

**Issue by flowcool** [CollinHeist/TitleCardMaker-Blueprints#106]
### Series Name

Peacemaker

### Series Year

2022

### Creator Username

flowcool

### Blueprint Description

Starwars card with PeacemakerForce-rgeKB font in yellow.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "star wars",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Peacemaker",
      "color": "#FBD609",
      "delete_missing": true,
      "file": "PeacemakerForce-rgeKB.otf"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![Peacemaker (2022) - S01E05](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/925f171a-e031-4eff-a764-72aafe1ffe76)

### Zip of Font Files

[PeacemakerForce-rgeKB.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12319823/PeacemakerForce-rgeKB.zip)

**Comment by CollinHeist** [comment]
Looks good! /create-blueprint
