### ISSUE TITLE
[Blueprint] Dexter: New Blood (2021)

### ISSUE THREAD

**Issue by flowcool** [CollinHeist/TitleCardMaker-Blueprints#107]
### Series Name

Dexter: New Blood

### Series Year

2021

### Creator Username

flowcool

### Blueprint Description

Olivier Card with Soda script bold font in official red color.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "olivier",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Dexter",
      "color": "#b11016",
      "delete_missing": true,
      "file": "Soda Script Bold Extras Regular.ttf",
      "interline_spacing": -100,
      "size": 1.6,
      "stroke_width": 0.6,
      "title_case": "upper"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card
![Dexter - New Blood (2021) - S01E06](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/2e9048d7-bbc5-4555-aece-1c9843298244)

### Zip of Font Files

[Soda Script Bold Extras Regular.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12319964/Soda.Script.Bold.Extras.Regular.zip)

**Comment by CollinHeist** [comment]
I think it might be worth trying to reduce the interline spacing on this so that the two lines of text aren't so far apart.

**Comment by flowcool** [comment]
> I think it might be worth trying to reduce the interline spacing on this so that the two lines of text aren't so far apart.

Good catch ! I didn't noticed that at the first sight ;)

I made a few others modifications too...
(was not expecting to go up -100 for the interline...seems huge)

**Comment by CollinHeist** [comment]
Yeah some fonts have some really aggressive spacing. Looks good! /create-blueprint
