### ISSUE TITLE
[Blueprint] Hawkeye (2021)

### ISSUE THREAD

**Issue by flowcool** [CollinHeist/TitleCardMaker-Blueprints#108]
### Series Name

Hawkeye

### Series Year

2021

### Creator Username

flowcool

### Blueprint Description

Olivier Card using howbai font in yellow as per TV show.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "olivier",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Hawkeye 2021",
      "color": "#FDE83F",
      "delete_missing": true,
      "file": "howbai-font.ttf",
      "interline_spacing": 40,
      "size": 1.6,
      "title_case": "lower",
      "vertical_shift": 50
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![Hawkeye (2021) - S01E06](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/4a2daa2d-8c72-4dd2-be7d-5edf1fd1d0d4)

### Zip of Font Files

[howbai-font.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12320401/howbai-font.zip)

**Comment by CollinHeist** [comment]
Nice - I was never able to find the matching font for this one. /create-blueprint
