### ISSUE TITLE
[Blueprint] Stranger Things (2016)

### ISSUE THREAD

**Issue by flowcool** [CollinHeist/TitleCardMaker-Blueprints#116]
### Series Name

Stranger Things

### Series Year

2016

### Blueprint Description

Olivier card & Benguiat Bold font in red.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted glass",
    "hide_season_text": true,
    "hide_episode_text": true,
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Stranger Things 2016",
      "color": "#EC1E24",
      "delete_missing": true,
      "file": "Benguiat Bold.ttf",
      "size": 0.8
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![Stranger Things (2016) - S01E05](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/d112304f-c411-43c7-9635-b1a89c4e59db)

### Zip of Font Files

[Benguiat Bold.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12323058/Benguiat.Bold.zip)

**Comment by CollinHeist** [comment]
If you'd like, you can use the `box_adjustments` extra to add some additional margin above the text (so it matches the other sides).

**Comment by flowcool** [comment]
I modifed with box_adjustments to 30 0 0 0...

But I have a weird feeling when there's one line vs 2 lines...
What do you think ?

![Stranger Things (2016) - S01E04](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/18259c98-c857-4998-ade0-14052801b0b3)
![Stranger Things (2016) - S01E01](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/58cc1752-5802-4139-ab0e-f3bb33126f87)

**Comment by CollinHeist** [comment]
Yeah I see, the spacing is a bit inconsistent.. I'll let you decide if you what to do! It might take me a little to find a fix for that, and might end up being font specific. If you want to leave it as is, make the change, or wait - whatever works for you

**Comment by flowcool** [comment]
I guess we can go like this ;) (I have created this one for pleasure as I don't even have it in my library ;) )

**Comment by CollinHeist** [comment]
Sounds good! Thanks for making it. If I get a chance to fix the box adjustment issue I'll update the Blueprint. /create-blueprint
