### ISSUE TITLE
[Blueprint] Cobra Kai

### ISSUE THREAD

**Issue by rtgurley** [CollinHeist/TitleCardMaker-Blueprints#118]
### Series Name

Cobra Kai

### Series Year

2018

### Creator Username

rtgurley, CollinHeist

### Blueprint Description

Standard Layout with custom font.  Credit to Dragonsys for the font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Cobra Kai",
      "color": "#FF0000",
      "delete_missing": true,
      "file": "Dead_Stock_Demo.ttf",
      "replacements_in": [
        "\u00e1",
        "(",
        ")"
      ],
      "replacements_out": [
        "a",
        "Part ",
        ""
      ]
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/52715600/2d600ce8-27ff-4e89-bbf5-17376672fa05)

### Zip of Font Files

[Dead_Stock_Demo.ttf.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12323220/Dead_Stock_Demo.ttf.zip)

**Comment by CollinHeist** [comment]
So in my past use of this Font, it does not have the characters `á`, `(` or `)`, which all appear in various titles. I've used these replacements:

`á`: `a`
`(`: `Part `
`)`: _nothing_

Want me to add those?

**Comment by rtgurley** [comment]
That would be great
