### ISSUE TITLE
[Blueprint] Ozark

### ISSUE THREAD

**Issue by rtgurley** [CollinHeist/TitleCardMaker-Blueprints#122]
### Series Name

Ozark

### Series Year

2017

### Creator Username

rtgurley

### Blueprint Description

Standard card format with custom font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Ozark",
      "color": "#FFFFFF",
      "delete_missing": true,
      "file": "ozark.otf"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/52715600/27b36fac-93b1-4fbf-a080-be12842270f3)

### Zip of Font Files

[ozark.otf.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12324946/ozark.otf.zip)

**Comment by CollinHeist** [comment]
Looks very good! /create-blueprint
