### ISSUE TITLE
[Blueprint] Outlander

### ISSUE THREAD

**Issue by BEisem** [CollinHeist/TitleCardMaker-Blueprints#127]
### Series Name

Outlander

### Series Year

2014

### Creator Username

Departed

### Blueprint Description

Tinted Frame card type with logo on top and episode title on bottom. Uses a font to match the series logo.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "top_element",
      "bottom_element"
    ],
    "extra_values": [
      "logo",
      "title"
    ],
    "template_ids": [],
    "font_color": "rgb(221, 161, 98)"
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Charlemagne Regular",
      "delete_missing": true,
      "file": "charlemagne-regular.otf"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/34734248/f2f2bc0a-8233-4fa3-9e9e-1fbae8023c34)

### Zip of Font Files

[charlemagne-regular.otf.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12328455/charlemagne-regular.otf.zip)

**Comment by CollinHeist** [comment]
Looks great! /create-blueprint

**Comment by CollinHeist** [comment]
Looks great! /create-blueprint

**Comment by CollinHeist** [comment]
Looks great! /create-blueprint
