### ISSUE TITLE
[Blueprint] The Lincoln Lawyer 2022

### ISSUE THREAD

**Issue by flowcool** [CollinHeist/TitleCardMaker-Blueprints#137]
### Series Name

The Lincoln Lawyer

### Series Year

2022

### Creator Username

flowcool

### Blueprint Description

Olivier card with Impact MT Regular font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "olivier",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "The Lincoln Lawyer (2022)",
      "delete_missing": true,
      "file": "Impact MT Regular.ttf",
      "stroke_width": 0.59
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![The Lincoln Lawyer (2022) - S01E04](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/67bdf3fa-d17e-4511-b9d0-442132034727)

### Zip of Font Files

[Impact MT Regular.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12334110/Impact.MT.Regular.zip)

**Comment by CollinHeist** [comment]
Looks good! /create-blueprint
