### ISSUE TITLE
[Blueprint] The Office (US)

### ISSUE THREAD

**Issue by BEisem** [CollinHeist/TitleCardMaker-Blueprints#140]
### Series Name

The Office (US)

### Series Year

2005

### Creator Username

Departed

### Blueprint Description

Uses the Olivier card type with the American Typewriter font to match The Office logo.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "olivier",
    "template_ids": [],
    "font_title_case": "lower"
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "American Typewriter Regular",
      "delete_missing": true,
      "file": "American Typewriter Regular.ttf"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/34734248/7682557d-e0f3-4dda-b066-971fbce242e0)

### Zip of Font Files

[American Typewriter Regular.ttf.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12340457/American.Typewriter.Regular.ttf.zip)

**Comment by CollinHeist** [comment]
Looks good! /create-blueprint
