### ISSUE TITLE
[Blueprint] She-Hulk: Attorney at Law

### ISSUE THREAD

**Issue by azuravian** [CollinHeist/TitleCardMaker-Blueprints#145]
### Series Name

She-Hulk: Attorney at Law

### Series Year

2022

### Blueprint Description

Comic card with She-Hulk green for the panels and random rotation.

### Blueprint

```json
{
  "series": {
    "card_type": "comic book",
    "extra_keys": [
      "banner_fill_color",
      "title_text_rotation_angle",
      "index_text_rotation_angle"
    ],
    "extra_values": [
      "rgba(127, 223, 119, 0.6)",
      "random[-4, 4]",
      "random[-4, 3]"
    ],
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/7379812/bcdd4ab3-571a-4afc-84a1-3f2a583a2ddd)

**Comment by CollinHeist** [comment]
Looks good! /create-blueprint
