### ISSUE TITLE
[Blueprint] Planet Earth II

### ISSUE THREAD

**Issue by azuravian** [CollinHeist/TitleCardMaker-Blueprints#147]
### Series Name

Planet Earth II

### Series Year

2016

### Blueprint Description

Landscape card with a darkened bounding box using a script font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "landscape",
    "extra_keys": [
      "add_bounding_box",
      "darken",
      "box_adjustments"
    ],
    "extra_values": [
      "True",
      "box",
      "-80 -10 -80 -10"
    ],
    "template_ids": [],
    "font_title_case": "title",
    "font_size": 1.5,
    "font_kerning": 0.15
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Mountain Brilliant",
      "delete_missing": true,
      "file": "Mountain Brilliant.ttf"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/7379812/ce97cfb7-2312-48b1-916b-3a6acececb33)

### Zip of Font Files

[Mountain Brilliant.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12425417/Mountain.Brilliant.zip)

**Comment by CollinHeist** [comment]
Nice! /create-blueprint
