### ISSUE TITLE
Friends (1994) proposal blueprint

### ISSUE THREAD

**Issue by flowcool** [CollinHeist/TitleCardMaker-Blueprints#15]
Hey guys,

I don't know to propose a new blueprint :(

Here it is, if you want to publish it.

[Friends (1994) Blueprint.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12050419/Friends.1994.Blueprint.zip)

**Comment by CollinHeist** [comment]
@flowcool Thank you! I'll get that added. FYI, the process for submitting them is described [here](https://titlecardmaker.readthedocs.io/en/latest/blueprints/).
