### ISSUE TITLE
[Blueprint] Batman: The Animated Series

### ISSUE THREAD

**Issue by Dante2202** [CollinHeist/TitleCardMaker-Blueprints#161]
### Series Name

Batman: The Animated Series

### Series Year

1992

### Blueprint Description

Batman: The Animated Series title cards, matches Batman font used.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Batman",
      "color": "yellow",
      "delete_missing": true,
      "file": "Batman.ttf",
      "size": 1.5,
      "title_case": "lower"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/101029157/4de28623-2671-4288-bef5-c855d539dd9a)

### Zip of Font Files

[Batman.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12469004/Batman.zip)

**Comment by CollinHeist** [comment]
Awesome - thank you!

**Comment by CollinHeist** [comment]
Awesome - thank you! /create-blueprint
