### ISSUE TITLE
[Blueprint] House of the Dragon

### ISSUE THREAD

**Issue by azuravian** [CollinHeist/TitleCardMaker-Blueprints#167]
### Series Name

House of the Dragon

### Series Year

2022

### Blueprint Description

Tinted frame card using font used for the show and a color matching the logo.  Logo at top of frame, title text at bottom.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "extra_keys": [
      "top_element",
      "bottom_element"
    ],
    "extra_values": [
      "logo",
      "title"
    ],
    "template_ids": [],
    "font_color": "rgb(241, 178, 103)",
    "font_title_case": "title"
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Trajan Pro",
      "delete_missing": true,
      "file": "Trajan Pro.ttf"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/7379812/d1f7fadb-3d10-4d07-983a-0bfa534b56c3)

### Zip of Font Files

[fonts.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12505333/fonts.zip)

**Comment by CollinHeist** [comment]
Nice! /create-blueprint
