### ISSUE TITLE
[Blueprint] ONE PIECE

### ISSUE THREAD

**Issue by azuravian** [CollinHeist/TitleCardMaker-Blueprints#174]
### Series Name

ONE PIECE

### Series Year

2023

### Blueprint Description

Blueprint for the Live Action ONEPIECE series on Netflix.  Uses the font from the original manga in the blue from the ONEPIECE logo.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "One Piece",
      "color": "rgb(0, 87, 137)",
      "delete_missing": true,
      "file": "one piece font.ttf",
      "size": 1.5,
      "title_case": "upper"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/7379812/e12406db-05a1-4b8c-809e-c1fd23b7ea2d)

### Zip of Font Files

[fonts.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12566646/fonts.zip)

**Comment by CollinHeist** [comment]
This reminds me I need to fix the Blueprints being case-sensitive. So I'll merge this now but I will have to edit it in a bit. Thanks! /create-blueprint
