### ISSUE TITLE
[Blueprint] The X-Files

### ISSUE THREAD

**Issue by ziggy73701** [CollinHeist/TitleCardMaker-Blueprints#178]
### Series Name

The X-Files

### Series Year

1993

### Creator Username

Ziggy73701

### Blueprint Description

Tinted Frame, using wider border.. logo moved to top and title at bottom using rounded typewriter font.

### Blueprint

```json
{
  "series": {
    "card_type": "tinted frame",
    "template_ids": [],
    "font_id": 0,
    "extra_keys": [
      "top_element",
      "bottom_element",
      "frame_width",
      "logo_size"
    ],
    "extra_values": [
      "logo",
      "title",
      "8",
      "1.2"
    ]
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "XFiles",
      "delete_missing": true,
      "file": "The X-Files.ttf"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/13312599/ba137a18-27f7-413b-9477-cd8060bbfe63)

### Zip of Font Files

[fonts.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12585237/fonts.zip)

**Comment by ziggy73701** [comment]
@CollinHeist I have looked over this and I am unsure why its throwing a error..

**Comment by CollinHeist** [comment]
@ziggy73701 That was a bug in the tests, I've fixed that and also removed the Template since it wasn't necessary (I merged those settings into the Series). Thanks for submitting this! /create-blueprint
