### ISSUE TITLE
[Blueprint] Foundation

### ISSUE THREAD

**Issue by lorissimo** [CollinHeist/TitleCardMaker-Blueprints#202]
### Series Name

Foundation

### Series Year

2021

### Creator Username

GrazedNutsack

### Blueprint Description

Simple "Standard" card type with a white "Foundation" font as the episode text.

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "font_id": 0,
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Foundation",
      "delete_missing": true,
      "file": "FoundationTitlesHand-SemiBold-v0.85.ttf"
    }
  ],
  "preview": "preview.png"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/80125655/f8ae76db-f113-488c-8838-7c44dcd5b281)

### Zip of Font Files

[fonts.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12685591/fonts.zip)

**Comment by CollinHeist** [comment]
Looks good! Thanks for submitting this. /create-blueprint
