### ISSUE TITLE
[Blueprint] 

### ISSUE THREAD

**Issue by lorissimo** [CollinHeist/TitleCardMaker-Blueprints#204]
### Series Name

ER

### Series Year

1994

### Creator Username

GrazedNutsack

### Blueprint Description

Simple "Standard" card type with a white lowercase "Letter Gothic Bold" font (similar to end credits font) as the episode text.

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "font_id": 0,
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "ER",
      "delete_missing": true,
      "file": "Letter_Gothic_Bold.ttf",
      "interline_spacing": 30,
      "size": 1.25,
      "title_case": "lower"
    }
  ],
  "preview": "preview.png"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/80125655/13700800-470a-4357-8ff8-3d1207d15238)

### Zip of Font Files

[fonts.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12693422/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks! Looks good. /create-blueprint

Oh and by the way you can always pick a different preview image, if you want (in case you didn't know)

**Comment by lorissimo** [comment]
> Thanks! Looks good. /create-blueprint
> 
> Oh and by the way you can always pick a different preview image, if you want (in case you didn't know)

You're welcome! That's good to know. I'll keep that in mind!
