### ISSUE TITLE
[Blueprint] The Bear

### ISSUE THREAD

**Issue by lorissimo** [CollinHeist/TitleCardMaker-Blueprints#209]
### Series Name

The Bear

### Series Year

2022

### Creator Username

GrazedNutsack

### Blueprint Description

Simple "Standard" card type with a white "HelveticaNeue Bold" Font as the title text.

### Blueprint

```json
{
  "series": {
    "card_type": "standard",
    "font_id": 0,
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "The Bear",
      "delete_missing": true,
      "file": "HelveticaNeue_Bold.ttf",
      "size": 1.25,
      "title_case": "upper"
    }
  ],
  "preview": "preview.png"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/80125655/26054294-6b03-4fbd-b9fb-54553a2515e6)

### Zip of Font Files

[fonts.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12719863/fonts.zip)

**Comment by CollinHeist** [comment]
Thanks so much! /create-blueprint
