### ISSUE TITLE
[Blueprint] 

### ISSUE THREAD

**Issue by thedinz** [CollinHeist/TitleCardMaker-Blueprints#223]
### Series Name

Cobra Kai

### Series Year

2018

### Creator Username

thedinz

### Blueprint Description

A simple Cobra Kai blueprint with fonts used from the poster

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "template_ids": [
      0
    ]
  },
  "episodes": {},
  "templates": [
    {
      "font_id": 0,
      "card_type": "anime",
      "name": "Cobra Kai",
      "filters": []
    }
  ],
  "fonts": [
    {
      "name": "Kobra Kai",
      "color": "#FFFF00",
      "delete_missing": true,
      "file": "cobra kai font.ttf",
      "size": 1.1
    }
  ],
  "preview": "Name of preview file here"
}
```

### Preview Title Card

![Screen Shot 2023-11-03 at 3 40 36 PM](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/68015411/bad4a481-05ce-407c-aa85-f6d403bed4df)

### Zip of Font Files

[fonts.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/13253994/fonts.zip)

**Comment by CollinHeist** [comment]
@thedinz Thanks for submitting this! Right now, only I can create the Blueprint - could you provide a different preview image? That one is blurry and pretty low resolution.

**Comment by thedinz** [comment]
> @thedinz Thanks for submitting this! Right now, only I can create the Blueprint - could you provide a different preview image? That one is blurry and pretty low resolution.

Damn let me see, its blurry because I have watched all episodes and the template uses Blurred Art for watched episodes, one moment let me see what I can do.

**Comment by CollinHeist** [comment]
You could use the previews on the Font or Template page, or just change the style and remake a single card - if not let me know I can try and make one

**Comment by thedinz** [comment]
> You could use the previews on the Font or Template page, or just change the style and remake a single card - if not let me know I can try and make one

Only problem is when I do that its a random image of meercats lol

Once I figure this out ill be banging out blueprints lol

**Comment by CollinHeist** [comment]
Yeah that's just a default image for those previews, lol. Changing the style of the Series then remaking a single Card will be easiest. I'll also add something so TCM does that for you

**Comment by CollinHeist** [comment]
I'm going to close this, feel free to re-submit to the [new repository](https://github.com/TitleCardMaker/Blueprints) - thanks!
