### ISSUE TITLE
[Blueprint] Arrested Development

### ISSUE THREAD

**Issue by rtgurley** [CollinHeist/TitleCardMaker-Blueprints#42]
### Series Name

Arrested Development

### Series Year

2003

### Blueprint Description

Standard card format using FF Blur font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Arrested Development",
      "color": "#FA5601",
      "delete_missing": true,
      "file": "BlurWeb-Medium W03 Regular.ttf"
    }
  ],
  "description": [
    "Descriptive information about this Blueprint"
  ],
  "creator": "Your (user)name here",
  "preview": "preview.jpg"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/52715600/49aece19-b3ea-40dd-b211-94f83f048c3c)

### Zip of Font Files

[BlurWeb-Medium W03 Regular.ttf.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12165083/BlurWeb-Medium.W03.Regular.ttf.zip)

**Comment by CollinHeist** [comment]
@rtgurley Looks great! Thank you.

/create-blueprint
