### ISSUE TITLE
[Blueprint] 1923

### ISSUE THREAD

**Issue by rtgurley** [CollinHeist/TitleCardMaker-Blueprints#43]
### Series Name

1923

### Series Year

2022

### Blueprint Description

Standard format card using the Boul Mich Regular font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "1923",
      "delete_missing": true,
      "file": "Boul Mich Regular.ttf",
      "stroke_width": 0.25
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/52715600/fe5c2fe1-3bc8-4e5e-8e10-19c7086a9371)

### Zip of Font Files

[Boul Mich Regular.ttf.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12165330/Boul.Mich.Regular.ttf.zip)

**Comment by CollinHeist** [comment]
@rtgurley You might try reducing the stroke width on this one, it looks like the super thin letters might be hard to read

**Comment by rtgurley** [comment]
Took the Stroke Width down to .25


![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/52715600/fe5c2fe1-3bc8-4e5e-8e10-19c7086a9371)

{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "1923",
      "delete_missing": true,
      "file": "Boul Mich Regular.ttf",
      "stroke_width": 0.25
    }
  ],
  "description": [
    "Descriptive information about this Blueprint"
  ],
  "creator": "Your (user)name here",
  "preview": "preview.jpg"
}

**Comment by CollinHeist** [comment]
That looks much more legible! Thanks

/test-blueprint
