### ISSUE TITLE
[Blueprint] Righteous Gemstones

### ISSUE THREAD

**Issue by rtgurley** [CollinHeist/TitleCardMaker-Blueprints#44]
### Series Name

The Righteous Gemstones

### Series Year

2019

### Blueprint Description

Standard format using the Festival BudayaXXXI font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Gemstones",
      "delete_missing": true,
      "file": "FestivalBudayaXXXI.otf"
    }
  ],
  "description": [
    "Descriptive information about this Blueprint"
  ],
  "creator": "Your (user)name here",
  "preview": "preview.jpg"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/52715600/718a7df0-1d43-49df-9988-8166262fe58d)

### Zip of Font Files

[FestivalBudayaXXXI.otf.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12165350/FestivalBudayaXXXI.otf.zip)

**Comment by CollinHeist** [comment]
Trying again! /create-blueprint
