### ISSUE TITLE
[Blueprint] Goldbergs

### ISSUE THREAD

**Issue by rtgurley** [CollinHeist/TitleCardMaker-Blueprints#47]
### Series Name

The Goldbergs

### Series Year

2013

### Blueprint Description

Standard Card format with Windsor Bold font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Goldbergs",
      "color": "#E7141D",
      "delete_missing": true,
      "file": "Windsor-Bold.ttf",
      "title_case": "source"
    }
  ],
  "description": [
    "Descriptive information about this Blueprint"
  ],
  "creator": "Your (user)name here",
  "preview": "preview.jpg"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/52715600/bf4d3cdc-dbfa-414f-a700-c893b3e80755)

### Zip of Font Files

[Windsor-Bold.ttf.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12165492/Windsor-Bold.ttf.zip)

**Comment by CollinHeist** [comment]
Very nice.

/create-blueprint
