### ISSUE TITLE
[Blueprint] The Big Bang Theory 2007

### ISSUE THREAD

**Issue by flowcool** [CollinHeist/TitleCardMaker-Blueprints#50]
### Series Name

The Big Bang Theory

### Series Year

2007

### Creator Username

flowcool

### Blueprint Description

Simple Big Bang Theory theme with font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "frame",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Big Bang Theory",
      "color": "#F6D65F",
      "delete_missing": true,
      "file": "Muro.otf",
      "title_case": "upper"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![The Big Bang Theory (2007) S05E03](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/1309da23-6ce4-456d-84c6-74cab651daec)

### Zip of Font Files

[Muro (2).zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12228577/Muro.2.zip)

**Comment by CollinHeist** [comment]
@flowcool So you're including an unnecessary Template in this one, and the actual assigned card type is standard, but your preview image is frame.

**Comment by CollinHeist** [comment]
I removed the unnecessary Template

/test-blueprint
