### ISSUE TITLE
[Blueprint] House MD

### ISSUE THREAD

**Issue by flowcool** [CollinHeist/TitleCardMaker-Blueprints#51]
### Series Name

House

### Series Year

2004

### Creator Username

flowcool

### Blueprint Description

Nice font used.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "frame",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "House MD",
      "delete_missing": true,
      "file": "House_M_D_Font_by_iTed.ttf",
      "interline_spacing": 20,
      "title_case": "title"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![House (2004) S04E04](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/0c3f01dc-18e7-4423-b167-9d028de6733c)

### Zip of Font Files

[House_M_D_Font_by_iTed.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12266543/House_M_D_Font_by_iTed.zip)

**Comment by CollinHeist** [comment]
Sorry I am working on the bot, seems like it's not printing the test results correctly. There is an unnecessary README file in the font zip
