### ISSUE TITLE
[Blueprint] HIMYM

### ISSUE THREAD

**Issue by flowcool** [CollinHeist/TitleCardMaker-Blueprints#52]
### Series Name

How I Met Your Mother

### Series Year

2005

### Creator Username

flowcool

### Blueprint Description

Simple Font based using Olivier cards.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "olivier",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "How I met your mother",
      "delete_missing": true,
      "file": "Dax Regular.otf",
      "title_case": "title"
    }
  ],
  "preview": "Name of preview file here"
}
```

### Preview Title Card

![How I Met Your Mother (2005) - S01E06](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/3d724ea9-ebbe-4b7f-a192-56c0cafb4c08)

### Zip of Font Files

[Dax Regular.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12266558/Dax.Regular.zip)

**Comment by CollinHeist** [comment]
I moved the Font casing to the actual Font, not as part of the Series.

/test-blueprint
