### ISSUE TITLE
[Blueprint] Scrubs

### ISSUE THREAD

**Issue by flowcool** [CollinHeist/TitleCardMaker-Blueprints#54]
### Series Name

Scrubs

### Series Year

2001

### Creator Username

flowcool

### Blueprint Description

Simple and colored Scrubs font based

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "frame",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Scrubs",
      "color": "#85F4F4",
      "delete_missing": true,
      "file": "tsslogo.ttf",
      "title_case": "title"
    }
  ],
  "preview": "My Old Lady"
}
```

### Preview Title Card

![Scrubs (2001) - S01E04](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/eaf86d05-5d1b-4af9-a948-9979763411f5)

### Zip of Font Files
[tsslogo.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12266575/tsslogo.zip)

**Comment by CollinHeist** [comment]
I have the same recommendations for this one, as the other Blueprint, want me to make those changes?

**Comment by flowcool** [comment]
Ok @CollinHeist ; I tried to rework on all - hoping I didn't miss anything. I guess it looks ok now ;)

**Comment by CollinHeist** [comment]
Alright thanks for making those changes; the last thing is to remove the Template completely (since it's not being used), and ideally change the preview image to have the English titles (same as The Bear) - LMK if you want me to do that.

**Comment by flowcool** [comment]
@CollinHeist : Finally 👍  I guess we are good for this one now ;)

**Comment by CollinHeist** [comment]
Perfect, thanks for doing that!

**Comment by CollinHeist** [comment]
Perfect! Thanks for doing that! /create-blueprint
