### ISSUE TITLE
[Blueprint] The Boys

### ISSUE THREAD

**Issue by flowcool** [CollinHeist/TitleCardMaker-Blueprints#55]
### Series Name

The Boys

### Series Year

2019

### Creator Username

flowcool

### Blueprint Description

StarWars cards with The Boys font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "star wars",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "The Boys",
      "color": "#EC1B17",
      "delete_missing": true,
      "file": "Charlie don't surf.ttf",
      "title_case": "upper"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![The Boys (2019) - S01E05](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/3d95eefd-7de3-4525-9053-0dad34cad8b3)

### Zip of Font Files

[Charlie don't surf.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12236647/Charlie.don.t.surf.zip)

**Comment by flowcool** [comment]
Hello @CollinHeist 
I tried to fix this one, but not sure what is the issue....
I remove language part and also non necessary files into font .zip file...

Hope it would be good now.

(is there a way to re run the workflow?)

**Comment by CollinHeist** [comment]
@flowcool Yes you can re-run the test by commenting `/test-blueprint`, I'll also remove the unnecessary Template
