### ISSUE TITLE
[Blueprint] The Bear

### ISSUE THREAD

**Issue by flowcool** [CollinHeist/TitleCardMaker-Blueprints#57]
### Series Name

The Bear

### Series Year

2022

### Creator Username

flowcool

### Blueprint Description

Simple theme with font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "The Bear",
      "color": "#FFF7C8",
      "delete_missing": true,
      "file": "HelveticaNeue Bold.ttf",
      "title_case": "title"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card
![The Bear (2022) - S01E05](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/8bb23eb6-05be-4c66-9d0d-68a3a1781e31)

### Zip of Font Files

[HelveticaNeue Bold.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12228726/HelveticaNeue.Bold.zip)

**Comment by CollinHeist** [comment]
For this one, I would recommend removing the French titles from the Blueprint as well as the preview title card, and then removing the unnecessary Template - want me to do that?

**Comment by CollinHeist** [comment]
So the issue is you're still including a Template that's not being used, and the preview title card has the French titles. Let me know if you want me to make those changes

**Comment by flowcool** [comment]
Same for this one, I think we're good and I took the lesson (hopefully). Please let me know in case of.

**Comment by CollinHeist** [comment]
Awesome - thanks again! /create-blueprint
