### ISSUE TITLE
[Blueprint] Fargo

### ISSUE THREAD

**Issue by flowcool** [CollinHeist/TitleCardMaker-Blueprints#58]
### Series Name

Fargo

### Series Year

2014

### Creator Username

flowcool

### Blueprint Description

Font based card

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Fargo",
      "color": "#993B3C",
      "delete_missing": true,
      "file": "Fargo_It_PERSONAL_USE_ONLY.otf",
      "size": 1.6,
      "title_case": "title"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![Fargo (2014) - S01E07](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/df1fa27f-4fd2-4f59-b0f1-52a785c66d94)

### Zip of Font Files

[Fargo_It_PERSONAL_USE_ONLY.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12228938/Fargo_It_PERSONAL_USE_ONLY.zip)

**Comment by CollinHeist** [comment]
So you seem to be including Templates that are not relevant to the actual Cards, you will need to remove these from the Blueprint (just FYI).

I did it for you on this one and some of the others, but if you have time to fix the others that'd be great
