### ISSUE TITLE
[Blueprint] 

### ISSUE THREAD

**Issue by BEisem** [CollinHeist/TitleCardMaker-Blueprints#61]
### Series Name

Game of Thrones

### Series Year

2011

### Creator Username

Departed

### Blueprint Description

Uses Logo Color Match with a Game of Thrones font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "azuravian/TitleColorMatch",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Game of Thrones",
      "delete_missing": true,
      "file": "Game of Thrones.ttf",
      "size": 0.85   
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/34734248/fe6d248a-3ee3-4365-977d-110fc5d7cb42)

### Zip of Font Files

[Game of Thrones.ttf.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12267888/Game.of.Thrones.ttf.zip)

**Comment by CollinHeist** [comment]
Stupid trailing commas.. /test-blueprint
