### ISSUE TITLE
[Blueprint] 

### ISSUE THREAD

**Issue by BEisem** [CollinHeist/TitleCardMaker-Blueprints#63]
### Series Name

Star Trek: The Next Generation

### Series Year

1987

### Creator Username

Departed

### Blueprint Description

A variation of the Tinted Frame card with a custom Star Trek font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted frame",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Star Trek",
      "delete_missing": true,
      "file": "Star Trek TNG-Title Regular.ttf"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/34734248/a7de9b7a-3395-47ce-8a5d-d911212cefbc)

### Zip of Font Files

[Star Trek TNG-Title Regular.ttf.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12268441/Star.Trek.TNG-Title.Regular.ttf.zip)

**Comment by CollinHeist** [comment]
Looks good! Thanks. I renamed the Font to Star Trek, just FYI. /create-blueprint
