### ISSUE TITLE
[Blueprint] Scrubs

### ISSUE THREAD

**Issue by CollinHeist** [CollinHeist/TitleCardMaker-Blueprints#79]
### Series Name

Scrubs

### Series Year

2001

### Blueprint Description

Standard card type with all the titles formatted like the logo - e.g. [title], using the Series font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "extra_keys": [
      "title_text_format"
    ],
    "extra_values": [
      "[{title_text}]"
    ],
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Scrubs",
      "delete_missing": true,
      "file": "tsslogo.ttf",
      "replacements_in": [
        "\u00e9",
        "\u00e0"
      ],
      "replacements_out": [
        "e",
        "a"
      ],
      "size": 1.4,
      "title_case": "lower",
      "vertical_shift": -10
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![Scrubs (2001) - S04E08](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/17693271/b2d17252-cf5d-4d1c-83f1-752105d5c057)

### Zip of Font Files

[tsslogo.ttf.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12285259/tsslogo.ttf.zip)

**Comment by CollinHeist** [comment]
test

**Comment by CollinHeist** [comment]
test again!

**Comment by CollinHeist** [comment]
a

**Comment by CollinHeist** [comment]
test

**Comment by CollinHeist** [comment]
test

**Comment by CollinHeist** [comment]
test

**Comment by CollinHeist** [comment]
test

**Comment by CollinHeist** [comment]
test

**Comment by CollinHeist** [comment]
test

**Comment by CollinHeist** [comment]
test

**Comment by CollinHeist** [comment]
test

**Comment by CollinHeist** [comment]
test

**Comment by CollinHeist** [comment]
test

**Comment by CollinHeist** [comment]
test

**Comment by CollinHeist** [comment]
test

**Comment by flowcool** [comment]
Hey @CollinHeist ....

I saw your blueprint which is way much better than mine ! (thanks for it) bu I have an issue using it, the brackets are not showing in the picture :( (it's properly configured and nothing into the log). I just imported your blueprint and deleted all cards...
![Scrubs (2001) - S02E04](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/7f094f91-ac97-4658-9504-afbdc2eb9a4d)

and the config:
![2023-08-14_16h25_20](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/19126314-876d-4798-a6e4-5b61a9abdf5f)



Does it ring a bell to you ?
(I'm not able to find any docs link to the config used: "title_text_format")

**Comment by CollinHeist** [comment]
@flowcool I added the `title_text_format` feature when I created this Blueprint, so you'll need to make sure you're on at least `v2.0-alpha.5.0-webui33` (the develop branch) for that to work

**Comment by flowcool** [comment]
Wooooooooooouhooooooooou !! It's working ! I like this one very much ! It's really the essence of the TV Show ;)
Thanks
