### ISSUE TITLE
[Blueprint] Barry (2018)

### ISSUE THREAD

**Issue by flowcool** [CollinHeist/TitleCardMaker-Blueprints#87]
### Series Name

Barry

### Series Year

2018

### Creator Username

flowcool

### Blueprint Description

Simple Oliver Card with proper font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "hide_season_text": true,
    "hide_episode_text": true,
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Barry TV Show",
      "color": "#DC1B22",
      "delete_missing": true,
      "file": "Barry TV Show - ChaparralPro-Bold.otf",
      "title_case": "upper"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![Barry (2018) - S01E04](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/861fee4f-5e94-470d-b50f-0260caac674a)

### Zip of Font Files

[Barry TV Show - ChaparralPro-Bold.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12287901/Barry.TV.Show.-.ChaparralPro-Bold.zip)

**Comment by CollinHeist** [comment]
Thanks! /create-blueprint
