### ISSUE TITLE
[Blueprint] Yellowstone

### ISSUE THREAD

**Issue by azuravian** [CollinHeist/TitleCardMaker-Blueprints#88]
### Series Name

Yellowstone

### Series Year

2018

### Creator Username

azuravian

### Blueprint Description

Frame title card using the Zilla Slab font (similar to the proprietary Yellowstone font) in the color of the series logo.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "frame",
    "template_ids": [],
    "font_size": 1.25
  },
  "episodes": {
    "s3e2": {
      "title": "Freight Trains & Monsters"
    },
    "s4e8": {
      "font_size": 1.1
    },
    "s5e1": {
      "font_size": 1.1
    },
    "s5e6": {
      "font_size": 1.1
    }
  },
  "templates": [],
  "fonts": [
    {
      "name": "Yellowstone",
      "color": "#ea9a27",
      "delete_missing": true,
      "file": "ZillaSlab-Medium.ttf",
      "title_case": "upper"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/7379812/58e933f9-fd5f-4101-99fd-b5af2c496567)

### Zip of Font Files

[ZillaSlab-Medium.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12294922/ZillaSlab-Medium.zip)

**Comment by CollinHeist** [comment]
@azuravian Thanks for the submission! I have it set so that only I can create the Blueprint (to catch any potential mistakes).

/create-blueprint
