### ISSUE TITLE
[Blueprint] Our Flag Means Death

### ISSUE THREAD

**Issue by rtgurley** [CollinHeist/TitleCardMaker-Blueprints#89]
### Series Name

Or Flag Means Death

### Series Year

2022

### Creator Username

rtgurley

### Blueprint Description

Standard Card type using (almost) series font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Our Flag Means Death",
      "color": "#FF0C95",
      "delete_missing": true,
      "file": "Seagram tfb.ttf",
      "title_case": "source"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/52715600/382cc8ad-a6b5-4159-a233-2935724efa2e)

### Zip of Font Files

[seagram_tfb.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12296018/seagram_tfb.zip)

**Comment by CollinHeist** [comment]
The bots need the Issue to start with [Blueprint], so I edited the title. /create-blueprint
