### ISSUE TITLE
[Blueprint] You

### ISSUE THREAD

**Issue by rtgurley** [CollinHeist/TitleCardMaker-Blueprints#91]
### Series Name

You

### Series Year

2018

### Creator Username

rtgurley

### Blueprint Description

Standard Card layout with a replica of the YOU font

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "standard",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "YOU",
      "delete_missing": true,
      "file": "YOU.ttf"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![You (2018) S01E05](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/52715600/d5ac222f-45de-4138-8066-6c353de8a821)

### Zip of Font Files

[YOU.ttf.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12297777/YOU.ttf.zip)

**Comment by CollinHeist** [comment]
Thanks! Cool font. /create-blueprint
