### ISSUE TITLE
[Blueprint] Watchmen

### ISSUE THREAD

**Issue by azuravian** [CollinHeist/TitleCardMaker-Blueprints#93]
### Series Name

Watchmen

### Series Year

2019

### Creator Username

azuravian, CollinHeist

### Blueprint Description

Utilizes CollinHeist's "Arrow" blueprint, replacing "Arrow" green with "Watchmen" yellow.

### Blueprint

```json
{
  "series": {
    "card_type": "comic book",
    "extra_keys": [
      "title_text_rotation_angle",
      "index_text_rotation_angle",
      "banner_fill_color"
    ],
    "extra_values": [
      "random[-4, 4]",
      "random[-4, -3]",
      "rgba(251,223,0,0.6)"
    ],
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![preview](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/7379812/b519a735-7856-4f7c-8f34-96f586aa4e26)

**Comment by CollinHeist** [comment]
Nice - I missed this one.

/create-blueprint
