### ISSUE TITLE
[Blueprint] Captain Caveman and the Teen Angels (1977)

### ISSUE THREAD

**Issue by flowcool** [CollinHeist/TitleCardMaker-Blueprints#95]
### Series Name

Captain Caveman and the Teen Angels

### Series Year

1977

### Creator Username

flowcool

### Blueprint Description

Olivier Card with the nice Captain Caveman font.

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "olivier",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Captain Caveman and the Teen Angels (1977)",
      "color": "#F7DE66",
      "delete_missing": true,
      "file": "Informal011BT-Roman.otf",
      "title_case": "upper"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![Capitaine Caverne (1977) - S01E01](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/652b324c-e035-4dfc-90b3-1c45bfa13bf3)

### Zip of Font Files

[Informal011BT-Roman.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12309632/Informal011BT-Roman.zip)

**Comment by CollinHeist** [comment]
Thank you! /create-blueprint
