### ISSUE TITLE
[Blueprint] The Queen’s Gambit (2020)

### ISSUE THREAD

**Issue by flowcool** [CollinHeist/TitleCardMaker-Blueprints#96]
### Series Name

The Queen’s Gambit

### Series Year

2020

### Creator Username

flowcool

### Blueprint Description

Anime Card & Platin Font in white color

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "anime",
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "The Queen\u2019s Gambit (2020)",
      "color": "white",
      "delete_missing": true,
      "file": "PlantinMTProSmBd.TTF",
      "title_case": "upper"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![Le Jeu de la dame (2020) - S01E07](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/228f0c00-14e5-424a-8097-cd1d78b8ac1f)

### Zip of Font Files

[PlantinMTProSmBd.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12311700/PlantinMTProSmBd.zip)

**Comment by CollinHeist** [comment]
Looks great. /create-blueprint
