### ISSUE TITLE
[Blueprint] Euphoria (US) (2019)

### ISSUE THREAD

**Issue by flowcool** [CollinHeist/TitleCardMaker-Blueprints#99]
### Series Name

Euphoria (US)

### Series Year

2019

### Creator Username

flowcool

### Blueprint Description

Tinted Card used with the font "Work Sans Extra Light" in lower case (free to use).

### Blueprint

```json
{
  "series": {
    "font_id": 0,
    "card_type": "tinted glass",
    "hide_season_text": true,
    "hide_episode_text": true,
    "template_ids": []
  },
  "episodes": {},
  "templates": [],
  "fonts": [
    {
      "name": "Euphoria (US) 2019",
      "color": "white",
      "delete_missing": true,
      "file": "Work Sans Extra Light.ttf",
      "title_case": "lower"
    }
  ],
  "preview": "preview.jpg"
}
```

### Preview Title Card

![Euphoria (US) (2019) - S01E03](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/7b4f8034-3b28-46bb-ae92-412d188fdc55)

### Zip of Font Files

[Work Sans Extra Light.zip](https://github.com/CollinHeist/TitleCardMaker-Blueprints/files/12312227/Work.Sans.Extra.Light.zip)

**Comment by CollinHeist** [comment]
Oh I love this, looks great with that font (which is generally hard to make visible). Have you thought about shifting the text down (with the vertical shift) so the text is a bit lower on the image? Since you're not using the season/episode text.

**Comment by flowcool** [comment]
Good catch ! I tried with a vertical shift of 50 and please find attached what gave.... not really good :(

(I'm looking each time for "official" font and color... sometimes it's looking better than others :P )

![Euphoria (US) (2019) - S01E03 (1)](https://github.com/CollinHeist/TitleCardMaker-Blueprints/assets/19570361/583f961b-961b-4068-98dd-2c3a69c6dc9c)

**Comment by CollinHeist** [comment]
Oh that might be a bug! I'll take a look and try to fix that, for now I'll create this one. /create-blueprint

**Comment by CollinHeist** [comment]
Alright I fixed that bug, I'll push that fix to develop right now. I'll also edit the Blueprint for you
